return {
	"nvimdev/lspsaga.nvim",
	event = "BufRead",
	opts = {
		ui = {
			border = "rounded",
			devicon = true,
			folder_level = 2,
			title = true,
			expand = "⊞",
			collapse = "⊟",
			code_action = "💡",
			actionfix = " ",
			lines = { "┗", "┣", "┃", "━", "┏" },
			kind = {},
		},
		lightbulb = {
			enable = true,
			enable_in_insert = false,
			sign = true,
			sign_priority = 40,
			virtual_text = true,
		},
		symbol_in_winbar = {
			enable = true,
			separator = " › ",
			hide_keyword = true,
			show_file = true,
			folder_level = 2,
			respect_root = false,
			color_mode = true,
		},
		diagnostic = {
			show_code_action = true,
			show_source = true,
			jump_num_shortcut = true,
			keys = {
				exec_action = "o",
				quit = "q",
				expand = "u",
				confirm = "<CR>",
			},
		},
		outline = {
			win_position = "right",
			win_with = "",
			win_width = 30,
			show_detail = true,
			auto_preview = true,
			auto_refresh = true,
			auto_close = true,
			custom_sort = nil,
			keys = {
				expand_or_collapse = "o",
				quit = "q",
			},
		},
	},
	dependencies = {
		"nvim-tree/nvim-web-devicons",
		"williamboman/mason-lspconfig.nvim",
	},
}
