return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  event = { "BufReadPost", "BufNewFile" },
  opts = {
    ensure_installed = {
      "lua",
      "vim",
      "vimdoc",
      "javascript",
      "typescript",
      "tsx",
      "bash",
      "html",
      "css",
      "scss",
      "python",
      "go",
      "markdown",
      "markdown_inline",
      "query",
      "regex",
      "http",
      "json",
      "jsonc",
      "xml",
    },
    sync_install = false,
    auto_install = true,
    highlight = { enable = true },
    indent = { enable = false },
  },
}
